# Generated by Django 6.0.4 on 2026-04-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_icecream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Топпинг')),
            ],
            options={
                'verbose_name': 'Топпинг',
                'verbose_name_plural': 'Топпинги',
            },
        ),
        migrations.CreateModel(
            name='PremiumIceCream',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bboard.food')),
                ('flavor', models.CharField(max_length=50, verbose_name='Вкус')),
                ('is_organic', models.BooleanField(default=False, verbose_name='Органическое')),
            ],
            options={
                'verbose_name': 'Премиум мороженое',
                'verbose_name_plural': 'Премиум мороженое',
            },
            bases=('bboard.food',),
        ),
        migrations.CreateModel(
            name='IceCreamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название набора')),
                ('icecreams', models.ManyToManyField(to='bboard.icecream', verbose_name='Мороженое')),
                ('toppings', models.ManyToManyField(to='bboard.topping', verbose_name='Топпинги')),
            ],
            options={
                'verbose_name': 'Набор мороженого',
                'verbose_name_plural': 'Наборы мороженого',
            },
        ),
    ]
