# Generated by Django 6.0.4 on 2026-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_food_topping_premiumicecream_icecreamset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.AlterModelOptions(
            name='icecreamset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='premiumicecream',
            options={},
        ),
        migrations.AddField(
            model_name='bb',
            name='content_bb',
            field=models.TextField(blank=True, null=True, verbose_name='BBCode описание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='icecreamset',
            name='icecreams',
            field=models.ManyToManyField(to='bboard.icecream'),
        ),
        migrations.AlterField(
            model_name='icecreamset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Набор'),
        ),
        migrations.AlterField(
            model_name='icecreamset',
            name='toppings',
            field=models.ManyToManyField(to='bboard.topping'),
        ),
        migrations.AlterField(
            model_name='premiumicecream',
            name='flavor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='premiumicecream',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
    ]
